openapi: "3.0.0"
info:
  version: 1.0.0
  title: Books
  description: Books
servers:
  - url: https://{hostname}/api/v1
    variables:
      hostname:
        default: anybook.online
paths:
  /books/{id}:
    get:
      operationId: getBookByID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Book id
      responses:
        '200':
          description: Get book by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

components:
  schemas:
    Book:
      type: object
      required:
        - title
      properties:
        title:
          type: string
    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string